name: Recipe Management App
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: install jest
        run: npm install --save jest
      - name: run jest tests
        run: npm run test