name: standard-pipeline
on: [push, pull_request]
jobs:
    generate-docs:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: JSdocs
              uses: andstor/jsdoc-action@v1.2.0
              with:
                  source_dir: ./source
                  recurse: true
                  output_dir: ./specs/documentation
    lint-code-base:
        # Set the agent to run on
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
              with:
                  # Full git history is needed to get a proper list of changed files within `super-linter`
                  fetch-depth: 0

            - name: Lint Code Base
              uses: github/super-linter@v4
              env:
                  VALIDATE_ALL_CODEBASE: false
                  DEFAULT_BRANCH: main
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                
    run-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "14"
            - run: npm install jest
            - run: npm test
            - name: Lighthouse CI Action
              uses: treosh/lighthouse-ci-action@v8

